---
- name: Deploy linux_tweet_app with NGINX + Let's Encrypt
  hosts: web
  become: true

  vars:
    domain_name: "localhost"
    app_image: "dockersamples/linux_tweet_app:latest"

  tasks:
    - name: Install required packages
      apt:
        name: [docker.io, docker-compose, python3-pip, certbot, python3-certbot-nginx]
        state: present
        update_cache: yes

    - name: Start linux_tweet_app container
      community.docker.docker_container:
        name: linux_tweet_app
        image: "{{ app_image }}"
        state: started
        restart_policy: always
        ports:
          - "8080:80"   # App listens internally on port 8080

    - name: Create NGINX config
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/linux_tweet_app
      notify: Restart NGINX

    - name: Enable site
      file:
        src: /etc/nginx/sites-available/linux_tweet_app
        dest: /etc/nginx/sites-enabled/linux_tweet_app
        state: link
        force: true
      notify: Restart NGINX

    - name: Remove default site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Restart NGINX
